package com.crowdar.examples.constants;

public class ClockifyHomeAddEntryConstants {

    public static final String START_TIME_LOCATOR = "ID:timeentry_start_time";
    public static final String END_TIME_LOCATOR = "ID:timeentry_end_time";
    public static final String START_RATE_LOCATOR = "XPATH://android.widget.LinearLayout[@content-desc=\"START\"]/android.widget.TextView";
    public static final String END_RATE_LOCATOR = "XPATH://android.widget.LinearLayout[@content-desc=\"END\"]/android.widget.TextView";
    public static final String TIME_HOURS_INPUT_LOCATOR = "XPATH:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.TimePicker/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.NumberPicker[1]/android.widget.EditText";
    public static final String TIME_MINUTE_INPUT_LOCATOR = "XPATH:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.TimePicker/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.NumberPicker[2]/android.widget.EditText";
    public static final String WORKING_DESCRIPTION_INPUT_LOCATOR = "ID:time_entry_description_input";
    public static final String SAVE_BUTTON_LOCATOR= "ID:floating_action_button";
    public static final String HOURS_NEXT_UP_BUTTON_LOCATOR = "XPATH:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.TimePicker/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.NumberPicker[1]/android.widget.Button[1]";
    public static final String HOURS_NEXT_DOWN_BUTTON_LOCATOR = "XPATH:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.TimePicker/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.NumberPicker[1]/android.widget.Button[2]";
    public static final String MINUTES_NEXT_UP_BUTTON_LOCATOR = "XPATH:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.TimePicker/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.NumberPicker[2]/android.widget.Button[1]";
    public static final String MINUTES_NEXT_DOWN_BUTTON_LOCATOR = "XPATH:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.TimePicker/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.NumberPicker[2]/android.widget.Button[2]";
    public static final String PREVIUS_MONTH_BUTTON_LOCATOR = "XPATH://android.widget.ImageButton[@content-desc=\"Previous month\"]";
    public static final String NEXT_MONTH_BUTTON_LOCATOR = "XPATH://android.widget.ImageButton[@content-desc=\"Next month\"]";
    public static final String DISCARD_BUTTON_LOCATOR = "ID:toolbar_discard_button";
    public static final String DISCARD_DISCARD_BUTTON_LOCATOR = "ID:discard_button";
    public static final String DISCARD_CANCEL_BUTTON_LOCATOR = "ID:cancel_button";
}
